### ISSUE TITLE
rosrun tianracer_gazebo judge_system_node.py

### ISSUE THREAD

**Issue by MrGoldminer** [tianbot/tianracer#56]
Traceback (most recent call last):
  File "/home/goldminer/tianbot_ws/src/tianracer/tianracer_gazebo/scripts/judge_system_node.py", line 17, in <module>
    from judge_system import judger
  File "judge_system.py", line 22, in init judge_system
ModuleNotFoundError: No module named 'md5'
这是为什么？
"judge_system.py"本地没有这个脚本

**Comment by sujit-168** [comment]
This module (md5.so) can only be found in the track compressed package released in the QQ competition official group chat 709078571 after July 28，you can join the group to find.
